### PR TITLE
Fix webpack bundling support

### LINKED ISSUE #1: Solved
Hi, i have annoying problem after install this plugin, i tried to run in my android phone and got error.

with 'import'
`import {Telephony} from "nativescript-telephony"`

result : 

```
app/main-view-model.ts(4,25): error TS2307: Cannot find module 'nativescript-telephony'.
TypeScript compiler failed with exit code 1
```

with 'var'
`var Telephony = require('nativescript-telephony');`

result :

```
TypeError: Telephony is not function
```

I've missed something?

Thank you

### PR DESCRIPTION
**Pull request by sis0k0**
related: https://github.com/NativeScript/nativescript-dev-webpack/issues/81
fixes: #1, #3

### CODE REVIEW

**Comment by roblav96** [comment]
@sis0k0 
```typescript
let you = 'winning'
```
Thank you =]

**Comment by abhayastudios** [comment]
Open source at its best ;)

Thanks both!

**Comment by abhayastudios** [comment]
Actually I am still getting an error after updating to the latest changes. Now I get the message `Could not find module 'nativescript-telephony'` even when just running `tns run ios`:

```
file:///app/pages/login.js:6:39: JS ERROR Error: Could not find module 'nativescript-telephony'. Computed path '<computed path>/app/tns_modules/nativescript-telephony'.

$ ls -la <computed path>/app/tns_modules/nativescript-telephony
total 64
drwxr-xr-x   9 joni  staff   306 Feb 24 21:01 .
drwxr-xr-x  55 joni  staff  1870 Feb 24 21:01 ..
-rw-r--r--   1 joni  staff    55 Feb 24 21:01 .npmignore
-rw-r--r--   1 joni  staff  1124 Feb 24 21:01 LICENSE
-rw-r--r--   1 joni  staff  2415 Feb 24 21:01 README.md
-rw-r--r--   1 joni  staff   124 Feb 24 21:01 index.d.ts
-rw-r--r--   1 joni  staff  6883 Feb 24 21:01 package.json
-rw-r--r--   1 joni  staff    51 Feb 24 21:01 telephony.d.ts
-rw-r--r--   1 joni  staff   330 Feb 24 21:01 tsconfig.json
```

Looks to me like somehow the code itself is not copied into the target directory? Maybe an issue in the new `package.json`?

I am invoking the plugin like this:

```
import {Telephony} from 'nativescript-telephony';

Telephony().then((info) => {
  console.dump(info);
}, (error) => {
  console.log('Unable to retrieve SIM info');
});
```

**Comment by roblav96** [comment]
@abhayastudios delete your `node_modules` folder and reinstall.

**Pull request merged**
